[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
kd-tree = "0.6.0"
rust-bert = "0.22.0"
serde = { version = "1.0.206", features = ["derive"] }
typenum = "1.17.0"
